# Proxy Server Configuration

# Server settings
server:
  listen_address: ":9999"

# Backend servers to connect using unix sockets
backends:
  - /var/run/api_1.sock
  - /var/run/api_2.sock

# Logging configuration
logging:
  enabled: true
  level: "info" # debug, info, warn, error
