# Proxy Server Configuration

# Server settings
server:
  listen_address: ":8080"
  read_timeout: "2s"      
  write_timeout: "2s"
  max_connections: 100000

# Keep-alive settings
# - enabled and client_timeout control TCP keep-alive for incoming connections
# - backend_timeout controls idle timeout for backend connections
keep_alive:
  enabled: true
  client_timeout: "30s"
  backend_timeout: "30s"
  max_requests_per_conn: 1000

# Backend servers to forward requests to
backends:
  - "http://localhost:8081"
  - "http://localhost:8082"

# Connection pool settings for backend connections
connection_pool:
  max_conns_per_host: 5000

# Logging configuration
logging:
  enabled: true
  level: "info"  # debug, info, warn, error

pre_warm:
  enabled: true
  requests_per_backend: 50